config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: :new
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 25 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 5, maximum: 50 },
            format: { with: VALID_EMAIL_REGEX }
  has_many :articles, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to perform that action!'
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def show; end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:notice] = 'Article was successfully created!'
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article updated successfully!'
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Article was successfully deleted!'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own article!'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully logged in!'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Wrong password or email, try again!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have successfully logged out!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :require_admin, only: %i[destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show; end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Galisoft Blog #{@user.username.capitalize}"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Update was successful!'
      redirect_to articles_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def destroy
    @user = user.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:alert] = 'You can only edit your own account'
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://www.gravator.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded-circle')
  end
end

app/views/articles/_articles.html.erb
<% obj.each do|article| %>
  <div class="jumbotron">
    <h3 class="display-4"><%= article.title %></h3>
    <p class="lead"><%= article.description %></p>
    <hr class="my-4">
    <p>
      <small>
        Created by: <%= article.user.username %>,
        created: <%= time_ago_in_words(article.created_at) %> ago,
        last updated: <%= time_ago_in_words(article.updated_at) %> ago
      </small>
    </p>
    <%= link_to 'Show', article_path(article), class: "btn btn-success" %>
    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
      <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-primary" %>
      <%= link_to 'Delete this article', article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete #{article.title}" }, class: "btn btn-danger" %>
    <% end %>
  </div>
<% end %>

app/views/articles/_form.erb
<% if @article.errors.any? %>
  <h3>The following errors prevented the article from getting <%= @article.new_record? ? "created!" : "updated" %></h3>
  <% @article.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class="container">
  <%= form_with(model: @article, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div>
      <%= form.submit(@article.new_record? ? "Create Article" : "Update article", class: "btn btn-success btn-lg") %>
    </div>
  <% end %>
</div>
<div class="d-grid gap-2 col-3 mx-auto">
  <%= link_to 'Cancel request and return to articles listing', articles_path %>
</div>

app/views/articles/edit.erb
<h2>Edit existing article</h2>
<%= render 'form' %>

app/views/articles/index.erb
<div class="container">
  <h2 class="text-center">Listing all articles</h2>
  <div>
    <%= will_paginate %>
  </div>
  <%= render 'articles/articles', obj: @articles %>
  <div>
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.erb
<h1 xmlns="http://www.w3.org/1999/html">New Article</h1>
<%= render 'form' %>

app/views/articles/show.erb
<h2>Showing selected  article</h2>
<div>
  <h3>Title: <%= @article.title %></h3>
</div>
<div>
  <p>Description: <%= @article.description %></p>
</div>
<div>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to 'Edit this article', edit_article_path(@article) %> |
    <%= link_to 'Delete this article', article_path(@article),
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this article?'} %>
  <% end %>
</div>
<div>
  <br/>
  <%= link_to 'Back to articles listing', articles_path %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do|name, message| %>
  <ul>
    <li><%= message %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galisoft Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.erb
<h1>Galisoft blog, About page!</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.erb
<div class="home text-center">
  <h1 class="display-4 text-light">Galisoft Blog</h1>
  <%= link_to "Sign up now", signup_path, class: "btn btn-success btn-lg" %>
</div>

app/views/shared/_footer.html.erb
<footer class="main-footer black_bg">
  <div class="container-fluid">
    <div class="row bg-dark">
      <div class="col d-flex justify-content-between bg-muted py-2">
        <ul class="d-flex justify-content-between align-items-center list-unstyled m-0">
          <li class="mx-2"><a href="#" class="text-decoration-none text-muted"><ion-icon name="logo-facebook"></ion-icon></a></li>
          <li class="mx-2"><a href="https://twitter.com/gango_anan" class="text-decoration-none text-muted"  ><ion-icon name="logo-twitter"></ion-icon></a></li>
          <li class="mx-2"><a href="https://www.linkedin.com/in/galiwango-ananiya/" class="text-decoration-none text-muted"><ion-icon name="logo-linkedin"></ion-icon></a></li>
          <li class="mx-2"><a href="#" class="text-decoration-none text-muted"><ion-icon name="logo-instagram"></ion-icon></a></li>
          <li class="mx-2"><a href="https://github.com/gango-anan" class="text-decoration-none text-muted"><ion-icon name="logo-github"></ion-icon></a></li>
        </ul>
        <p class="text-white small m-0">Powered by <i><strong>galisoft</strong></i></p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'galisoft blog', root_path, class: 'navbar-brand', id: 'logo' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'New Article', new_article_path, class: "dropdown-item" %></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%  if current_user.admin? %>
                <%= "Admin" %>
              <% else %>
                <%= current_user.username %>
              <% end %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Edit profile', edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to 'Show profile', user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
  <h3>The following errors prevented the user from getting created!</h3>
  <% @user.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>
<%= form_with(model: @user, local: true) do|form| %>
  <div class="mb-3">
    <%= form.label :username, class: "form-label" %>
    <%= form.text_field :username, placeholder: 'Enter username', autofocus: true, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control", placeholder: 'email@samplemail.com' %>
  </div>
  <% if @user.new_record? %>
    <div class="mb-3">
      <%= form.label :password, class: "form-label" %>
      <%= form.password_field :password, class: "form-control", placeholder: 'password' %>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation, class: "form-label" %>
      <%= form.password_field :password_confirmation, class: "form-control", placeholder: 'password' %>
    </div>
  <% else %>
    <div class="mb-3">
      <%= form.label :password, class: "form-label" %>
      <%= form.password_field :password, class: "form-control", placeholder: 'password' %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-success btn-md") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2 class="text-center">Update user</h2>
<%= render 'user_form' %>

app/views/users/index.html.erb
<h2>All Galisoft Bloggers</h2>
<% @users.each do|user| %>
  <ul class="listing">
    <div class="row">
      <div>
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li>
          <small>
            <%= pluralize(user.articles.count, 'article') if user.articles %>
          </small>
          <% if logged_in? and current_user.admin? %>
            <li>
              <%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles?"} %>
            </li>
          <% end %>
        </li>
      </div>
    </div>
  </ul>
<% end %>

app/views/users/new.html.erb
<h2 class="text-center">Sign up for Galisoft Blog</h2>
<%= render 'user_form' %>

app/views/users/show.html.erb
<h2 class="text-center">Welcome to <%= @user.username %>&#39;s page</h2>
<div>
  <div>
    <%= gravatar_for @user %>
  </div>
</div>
<h3 class="text-center"><%= @user.username %>&#39;s articles</h3>
<%= render 'articles/articles', obj: @user.articles %>